<?php defined('SYSPATH') or die('No direct access allowed.');


/**
 * custom options for the theme
 * @var array
 */
return array(   'premium' => array( 'type'      => 'numeric',
                                                'display'   => 'hidden',
                                                'default'   => 1,
                                                'required'  => TRUE,
                                                'category'  => __('General')),

                'theme' => array(	       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Change the color theme'),
                                            'options'   => array(   'default'   => 'Blue',
                                                                    'green'     => 'Green',
                                                                    'orange'    => 'Orange',
                                                                ),
                                            'default'   => 'default',
                                            'required'  => TRUE,
                                            'category'  => __('Color'),
                ),

                'fixed_toolbar' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Header tool bar gets fixed in the top'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'logo_url' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your Logo. Recommended size 250px x 40px and file format PNG. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General'),),

                'favicon_url' => array(     'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your favicon. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General'),),

                'apple-touch-icon' => array( 'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your apple-touch-icon. Recommended size 57px x 57px. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General'),),

                'default_profile_image' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your default profile image.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                'num_home_latest_ads' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Numbers of ads to display in home slider'),
                                            'default'   => 21,
                                            'required'  => TRUE,
                                            'category'  => __('Homepage')),

                'sidebar_position' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Where you want the sidebar to appear'),
                                            'options'   => array(   'none' => __('None'),
                                                                    'right' => __('Right side'),
                                                                    'left'  => __('Left side'),
                                                                ),
                                            'default'   => 'right',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'header_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Header banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'footer_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Footer banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'listing_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Listing random position banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Layout')),
                'homepage_html' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage Only Header, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
                'homepage_img' => array(       'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Homepage Banner Image'),
                                                    'default'   => 'http://klekt-assets.s3.amazonaws.com/img/klekt_banner_v2_2.jpg',
                                                    'category'  => __('Homepage'),),
                'homepage_text_1' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage hero title, allows HTML'),
                                            'default'   => __('Homepage hero title'),
                                            'category'  => __('Homepage')),
                'homepage_text_2' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage hero subtitle, allows HTML'),
                                            'default'   => __('Homepage hero subtitle'),
                                            'category'  => __('Homepage')),
                'homepage_cta_1' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage publish new CTA'),
                                            'default'   => __('Publish new'),
                                            'category'  => __('Homepage')),
                'homepage_cta_2' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage listing CTA'),
                                            'default'   => __('Listing'),
                                            'category'  => __('Homepage')),
                'facebook_link' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Facebook link'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'twitter_link' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Twitter link'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'instagram_link' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Instagram link'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'hide_description_icon' => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Hide icon on category/location description'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0' => __('No'),
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE),
);
