<?php defined('SYSPATH') or die('No direct access allowed.');


/**
 * custom options for the theme
 * @var array
 */
return array(   'premium' => array( 'type'      => 'numeric',
                                                'display'   => 'hidden',
                                                'default'   => 1,
                                                'required'  => TRUE,
                                                'category'  => __('General')),

                'theme' => array(   'type'      => 'text',
                                    'display'   => 'select',
                                    'label'     => __('Change the color scheme and style of the theme'),
                                    'options'   => array(   'oc'        => 'OC',
                                                            'red'        => 'Red',
                                                            'blue'        => 'Blue',
                                                            'amber'        => 'Amber',
                                                            'orange'        => 'Orange',
                                                            'teal'        => 'Teal',
                                                        ),
                                    'default'   => 'oc',
                                    'required'  => TRUE,
                                    'category'  => __('Color')),
                'custom_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Or select your own color. Will overwrite the predefined color scheme. Leave blank if you want to use the predefined color scheme.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

                'custom_color_hover' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Hover color of custom color'),
                                            'default'   => '',
                                            'category'  => __('Color')),
                'theme_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color that styles the mobile browser interface.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

                /*'admin_theme' => array(     'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Change the admin color theme'),
                                            'options'   => array(   'bootstrap' => 'Original',
                                                                    'cerulean'  => 'Dark Blue',
                                                                    'cosmo'     => 'Metro Style',
                                                                    'spacelab'  => 'Nice Grey',
                                                                    'united'    => 'Purple / Orange',
                                                                ),
                                            'default'   => 'bootstrap',
                                            'required'  => TRUE),*/
                'body_font' => array(       'type'      => 'text',
                            'display'   => 'select',
                            'label'     => __('Body Font'),
                            'options'   => array(   '' => 'Default',
                                                    '//fonts.googleapis.com/css?family=Open+Sans:400,700|Open Sans' => 'Open Sans',
                                                    '//fonts.googleapis.com/css?family=Roboto:400,700|Roboto' => 'Roboto',
                                                    '//fonts.googleapis.com/css?family=Lato:400,700|Lato' => 'Lato',
                                                    '//fonts.googleapis.com/css?family=Slabo+27px:400,700|Slabo 27px' => 'Slabo 27px',
                                                    '//fonts.googleapis.com/css?family=Oswald:400,700|Oswald' => 'Oswald',
                                                    '//fonts.googleapis.com/css?family=Roboto+Condensed:400,700|Roboto Condensed' => 'Roboto Condensed',
                                                    '//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source Sans Pro' => 'Source Sans Pro',
                                                    '//fonts.googleapis.com/css?family=Montserrat:400,700|Montserrat' => 'Montserrat',
                                                    '//fonts.googleapis.com/css?family=Lora:400,700|Lora' => 'Lora',
                                                    '//fonts.googleapis.com/css?family=PT+Sans:400,700|PT Sans' => 'PT Sans',
                                                    '//fonts.googleapis.com/css?family=Raleway:400,700|Raleway' => 'Raleway',
                                                    '//fonts.googleapis.com/css?family=Open+Sans+Condensed:400,700|Open Sans Condensed' => 'Open Sans Condensed',
                                                    '//fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid Sans' => 'Droid Sans',
                                                    '//fonts.googleapis.com/css?family=Ubuntu:400,700|Ubuntu' => 'Ubuntu',
                                                    '//fonts.googleapis.com/css?family=Droid+Serif:400,700|Droid Serif' => 'Droid Serif',
                                                    '//fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto Slab' => 'Roboto Slab',
                                                    '//fonts.googleapis.com/css?family=Merriweather:400,700|Merriweather' => 'Merriweather',
                                                    '//fonts.googleapis.com/css?family=Arimo:400,700|Arimo' => 'Arimo',
                                                    '//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700|PT Sans Narrow' => 'PT Sans Narrow',
                                                    '//fonts.googleapis.com/css?family=Noto+Sans:400,700|Noto Sans' => 'Noto Sans'
                                                                ),
                                            'default'   => '',
                                            'category'  => __('Typography')),

                'boxed_layout' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Boxed or wide layout'),
                                            'options'   => array(   '1' => __('Boxed'),
                                                                    '0'  => __('Wide'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'breadcrumb' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display breadcrumb'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'logo_url' => array(        'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your logo. Recommended height is 45px and file format PNG. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'favicon_url' => array(     'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your favicon. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'apple-touch-icon' => array( 'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your apple-touch-icon. Recommended size 57px x 57px. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General'),),
                'default_profile_image' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your default profile image.'),
                                            'default'   => '',
                                            'category'  => __('General')),
               'num_home_latest_ads' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Numbers of ads to display in home grid'),
                                            'default'   => 21,
                                            'required'  => TRUE,
                                            'category'  => __('Homepage')),
               'homepage_slider' => array(   'type'      => 'text',
                                        'display'   => 'select',
                                        'label'     => __('Display flickerplate slider on homepage'),
                                        'options'   => array(
                                                                '0'  => __('Yes'),
                                                                '1' => __('No'),
                                                                ),
                                            'default'   => '1',
                                            'category'  => __('Homepage')),
               'homepage_slider_image_1' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the url of image of the first slide'),
                                            'default'   => 'https://c1.staticflickr.com/9/8498/8285850247_23d50ecf07_k.jpg',
                                            'category'  => __('Homepage')),
               'homepage_slider_title_1' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h1 title of the first slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'homepage_slider_subtitle_1' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h3 title of the first slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'homepage_slider_image_2' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the url of image of the second slide'),
                                            'default'   => 'http://photoeverywhere.co.uk/east/japan/tokyo/tokyo_night.jpg',
                                            'category'  => __('Homepage')),
               'homepage_slider_title_2' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h1 title of the second slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'homepage_slider_subtitle_2' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h3 title of the second slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'homepage_slider_image_3' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the url of image of the third slide'),
                                            'default'   => 'https://c1.staticflickr.com/3/2685/4408159729_fce6fbbb26_o.jpg',
                                            'category'  => __('Homepage')),
               'homepage_slider_title_3' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h1 title of the third slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'homepage_slider_subtitle_3' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If homepage slider is active, the h3 title of the third slide'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
               'categories_on_homepage' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Show categories on homepage'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Homepage')),

                'sidebar_position' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Where you want the sidebar to appear'),
                                            'options'   => array(   'none' => __('None'),
                                                                    'right' => __('Right side'),
                                                                    'left'  => __('Left side'),
                                                                ),
                                            'default'   => 'none',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'dark_listing' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Select light or dark listings'),
                                            'options'   => array(   '1' => __('Dark'),
                                                                    '0'  => __('Light'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'listing_display' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Select the listing style'),
                                            'options'   => array(   'title-in-ad' => __('Title in ad'),
                                                                    'title-above-ad' => __('Title above ad'),
                                                                    'title-below-ad' => __('Title below ad'),
                                                                ),
                                            'default'   => 'title-in-ad',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'listing_clickable' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Make entire list item clickable on homepage'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'listing_extra_info' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('For every listing it shows the price in the bottom extra info. Next to the price you can select a second option to show.'),
                                            'options'   => array(   'views' => __('Number of views'),
                                                                    'location' => __('Location of ad'),
                                                                    'user' => __('Owner of ad'),
                                                                ),
                                            'default'   => 'views',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'listing_slider' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display slider in listing'),
                                            'options'   => array(
                                                                    '0'  => __('None'),
                                                                    '1' => __('Default'),
                                                                    '2'  => __('Featured'),
                                                                    '3' => __('Featured Random')
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),
                'listgrid' => array(   'type'      => 'text',
                                        'display'   => 'select',
                                        'label'     => __('Default state for list/grid in listing'),
                                        'options'   => array(
                                                                '0'  => __('Grid'),
                                                                '1' => __('List'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),
                'infinite_scroll' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Infinite scroll'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'category_badge' => array(  'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Disable category counter badge'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),
                'hide_description_icon' => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Hide icon on category/location description'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0' => __('No'),
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),
                'bannergroup' => array(    'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Show bannergroup above footer'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),
                'maintitle_bannergroup' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If bannergroup is active, text of the H1 title'),
                                            'category'  => __('Layout')),
                'subtitle_bannergroup' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('If bannergroup is active, text of the H4 subtitle'),
                                            'category'  => __('Layout')),
                'footer_pages' => array(    'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Hide page links on footer'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),
                'landing_single_ad' =>array('type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Hide header and footer on single ad, user profile page and guest checkout page'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),
                'header_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Header banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'footer_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Footer banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'listing_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Listing random position banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Listing')),
                'homepage_html' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage Only Header, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
                'rtl' => array(             'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Content shift right to left'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),
                'cdn_files' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Uses CDN for CSS/JS'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),

                'amp_top_bar_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color that styles the top bar of the AMP pages.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

                'amp_custom_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color of the AMP pages.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

);