<?php defined('SYSPATH') or die('No direct access allowed.');


/**
 * custom options for the theme
 * @var array
 */
return array(   'premium'               => array(   'type'      => 'numeric',
                                                    'display'   => 'hidden',
                                                    'default'   => 1,
                                                    'required'  => TRUE,
                                                    'category'  => __('General')),
                'theme'                  => array(  'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Change the color scheme and style of the theme'),
                                                    'options'   => array('default'    => 'Default',
                                                                        'orange'     => 'Orange',
                                                                        'red'	=> 'Red',
                                                                        'green' => 'Green',
                                                                        'blue'	=> 'Blue',
                                                                        // 'red-blue'	=> 'Red-Blue',
                                                                        'orange-blue'	=> 'Orange-Blue',
                                                                        ),
                                                    'default'   => 'oc',
                                                    'required'  => TRUE,
                                                    'category'  => __('Color')),
                'theme_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color that styles the mobile browser interface.'),
                                            'default'   => '',
                                            'category'  => __('Color')),
                'body_font' => array(       'type'      => 'text',
                            'display'   => 'select',
                            'label'     => __('Body Font'),
                            'options'   => array(   '' => 'Default',
                                                    '//fonts.googleapis.com/css?family=Open+Sans:400,700|Open Sans' => 'Open Sans',
                                                    '//fonts.googleapis.com/css?family=Roboto:400,700|Roboto' => 'Roboto',
                                                    '//fonts.googleapis.com/css?family=Lato:400,700|Lato' => 'Lato',
                                                    '//fonts.googleapis.com/css?family=Slabo+27px:400,700|Slabo 27px' => 'Slabo 27px',
                                                    '//fonts.googleapis.com/css?family=Oswald:400,700|Oswald' => 'Oswald',
                                                    '//fonts.googleapis.com/css?family=Roboto+Condensed:400,700|Roboto Condensed' => 'Roboto Condensed',
                                                    '//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source Sans Pro' => 'Source Sans Pro',
                                                    '//fonts.googleapis.com/css?family=Montserrat:400,700|Montserrat' => 'Montserrat',
                                                    '//fonts.googleapis.com/css?family=Lora:400,700|Lora' => 'Lora',
                                                    '//fonts.googleapis.com/css?family=PT+Sans:400,700|PT Sans' => 'PT Sans',
                                                    '//fonts.googleapis.com/css?family=Raleway:400,700|Raleway' => 'Raleway',
                                                    '//fonts.googleapis.com/css?family=Open+Sans+Condensed:400,700|Open Sans Condensed' => 'Open Sans Condensed',
                                                    '//fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid Sans' => 'Droid Sans',
                                                    '//fonts.googleapis.com/css?family=Ubuntu:400,700|Ubuntu' => 'Ubuntu',
                                                    '//fonts.googleapis.com/css?family=Droid+Serif:400,700|Droid Serif' => 'Droid Serif',
                                                    '//fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto Slab' => 'Roboto Slab',
                                                    '//fonts.googleapis.com/css?family=Merriweather:400,700|Merriweather' => 'Merriweather',
                                                    '//fonts.googleapis.com/css?family=Arimo:400,700|Arimo' => 'Arimo',
                                                    '//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700|PT Sans Narrow' => 'PT Sans Narrow',
                                                    '//fonts.googleapis.com/css?family=Noto+Sans:400,700|Noto Sans' => 'Noto Sans'
                                                                ),
                                            'default'   => '//fonts.googleapis.com/css?family=Roboto:400,700|Roboto',
                                            'category'  => __('Typography')),
                'breadcrumb' => array(              'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Display breadcrumb'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                        ),
                                                    'default'   => '1',
                                                    'required'  => TRUE,
                                                    'category'  => __('Layout')),

                'fixed_toolbar' => array(           'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Header tool bar gets fixed in the top'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                        ),
                                                    'default'   => '1',
                                                    'required'  => TRUE,
                                                    'category'  => __('Layout')),

                'header_search' => array(           'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Search bar on header'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                        ),
                                                    'default'   => '1',
                                                    'required'  => TRUE,
                                                    'category'  => __('Layout')),

                'logo_url'              => array(   'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Upload your logo. Recommended size 250px x 40px. Leave blank for none.'),
                                                    'default'   => '',
                                                    'category'  => __('General')
                                                ),
                'favicon_url'           => array(   'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Upload your favicon. Leave blank for none.'),
                                                    'default'   => '',
                                                    'category'  => __('General')),

                'apple-touch-icon' 		=> array( 	'type'      => 'text',
		                                            'display'   => 'logo',
		                                            'label'     => __('Upload your apple-touch-icon. Recommended size 57px x 57px. Leave blank for none.'),
		                                            'default'   => '',
                                                    'category'  => __('General')),

                'default_profile_image' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your default profile image.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                'num_home_latest_ads'   => array(   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Numbers of ads to display on homepage. Recommended 30.'),
                                                    'default'   => 30,
                                                    'required'  => TRUE,
                                                    'category'  => __('Homepage')),
                'sidebar_position' => array(        'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Where you want the sidebar to appear'),
                                                    'options'   => array(   'right' => __('Right side'),
                                                                            'left'  => __('Left side'),
                                                                            'none'  => __('None'),
                                                                        ),
                                                    'default'   => 'none',
                                                    'required'  => TRUE,
                                                    'category'  => __('Layout')),
                'landing_single_ad' =>array         ('type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Hide header and footer on single ad and user profile page'),
                                                    'options'   => array(
                                                                            '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Layout')),
                'home_slogan'           => array(	   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage site slogan'),
                                                    'default'   => 'Search and place ads easily with us',
                                                    'category'  => __('Homepage')
                                                ),
                'home_description'      => array(	   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage site description'),
                                                    'default'   => 'Yclas can help you start a website and turn it into a fully customizable classifieds site within a few minutes.',
                                                    'category'  => __('Homepage')
                                                ),
                'infinite_scroll'       => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Infinite scroll'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),
                'listgrid'              => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Default state for list/grid in listing'),
                                                    'options'   => array(
                                                                    '0'  => __('Grid'),
                                                                    '1' => __('List'),
                                                                    ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),
                'header_ad'             => array(   'type'      => 'text',
                                                    'display'   => 'textarea',
                                                    'label'     => __('Header banner, allows HTML'),
                                                    'default'   => '',
                                                    'category'  => __('General')),
                'footer_ad'             => array(   'type'      => 'text',
                                                    'display'   => 'textarea',
                                                    'label'     => __('Footer banner, allows HTML'),
                                                    'default'   => '',
                                                    'category'  => __('General')),
                'listing_ad'            => array(   'type'      => 'text',
                                                    'display'   => 'textarea',
                                                    'label'     => __('Listing random position banner, allows HTML'),
                                                    'default'   => '',
                                                    'category'  => __('Listing')),
                'homepage_html'         => array(   'type'      => 'text',
                                                    'display'   => 'textarea',
                                                    'label'     => __('Homepage Only Header, allows HTML'),
                                                    'default'   => '',
                                                    'category'  => __('Homepage')),
                'rtl'                   => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Content shift right to left'),
                                                    'options'   => array(   '1' => __('Yes'),
                                                                            '0'  => __('No'),
                                                                ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('General')),

                'listing_slider'        => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Display slider in listing'),
                                                    'options'   => array(
                                                                            '0'  => __('None'),
                                                                            '1' => __('Default'),
                                                                            '2'  => __('Featured'),
                                                                            '3' => __('Featured Random')
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),

                'listing_slider_mobile'        => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Display listing slider on mobile devices'),
                                                    'options'   => array(
                                                                            '0'  => __('Yes'),
                                                                            '1' => __('No')
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),

                'closed_auctions'   => array(   	'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Show latest closed auctions on homepage'),
                                                    'options'   => array(
                                                                            '0' => __('No'),
                                                                            '1'  => __('Yes')
                                                                        ),
                                                    'default'   => '1',
                                                    'required'  => TRUE,
                                                    'category'  => __('Homepage')),

                'highest_bidder_homepage'   => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Display highest bidder username in the homepage'),
                                                    'options'   => array(
                                                                            '0'  => __('Yes'),
                                                                            '1' => __('No')
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Homepage')),

                'highest_bidder_listing'        => array(   'type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Display highest bidder username in the listing page'),
                                                    'options'   => array(
                                                                            '0'  => __('Yes'),
                                                                            '1' => __('No')
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Listing')),


// Single page options

                'show_best_bidder'        => array('type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Show best bidder and number of bids'),
                                                    'options'   => array(
                                                                            '0'  => __('None'),
                                                                            '1' => __('Only the number of bids'),
                                                                            '2' => __('Only the best bidder username, first and last letter visible'),
                                                                            '3' => __('Only the best bidder username'),
                                                                            '4' => __('Number of bids and best bidder username, first and last letter visible'),
                                                                            '5'  => __('Number of bids and best bidder username')
                                                                        ),
                                                    'default'   => '4',
                                                    'required'  => TRUE,
                                                    'category'  => __('Ad details page')),


                'show_starting_price'       => array('type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Show starting price'),
                                                    'options'   => array(
                                                                            '0'  => __('No'),
                                                                            '1' => __('Yes')
                                                                        ),
                                                    'default'   => '0',
                                                    'required'  => TRUE,
                                                    'category'  => __('Ad details page')),

                'show_bids_history'        => array('type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Show Bids history in pop-up - <a target="_blank" href="https://i0.wp.com/yclas.nyc3.digitaloceanspaces.com/images/cms/1501511450.realty-splash.png">Click to view</a>'),
                                                    'options'   => array(
                                                                            '0'  => __('None'),
                                                                            '1' => __('Only the best bidder username, first and last letter visible'),
                                                                            '2' => __('Only the best bidder username'),
                                                                            '3' => __('Best three bidders username, first and last letter visible'),
                                                                            '4' => __('Best three bidders username'),
                                                                            '5'  => __('All the bidders username, only first and last letter visible'),
                                                                            '6' => __('All the bidders, full username visible')
                                                                        ),
                                                    'default'   => '5',
                                                    'required'  => TRUE,
                                                    'category'  => __('Ad details page')),

                'click_reveal_phone'        => array('type'      => 'text',
                                                    'display'   => 'select',
                                                    'label'     => __('Show/hide phone number in the ad page'),
                                                    'options'   => array(
                                                                            '0'  => __('Don\'t show the phone number'),
                                                                            '1' => __('Require click to reveal phone number'),
                                                                            '2' => __('Show phone number')
                                                                        ),
                                                    'default'   => '1',
                                                    'required'  => TRUE,
                                                    'category'  => __('Ad details page')),





);