<?php defined('SYSPATH') or die('No direct access allowed.');


/**
 * custom options for the theme
 * @var array
 */
return array(   'premium' => array( 'type'      => 'numeric',
                                                'display'   => 'hidden',
                                                'default'   => 1,
                                                'required'  => TRUE,
                                                'category'  => __('General')),
                'theme' => array(   'type'      => 'text',
                                    'display'   => 'select',
                                    'label'     => __('Change the color scheme and style of the theme'),
                                    'options'   => array(   'original' => 'Original',
                                                            'wedding' => 'Wedding',
                                                            'happy' => 'Happy',

                                                                ),
                                            'default'   => 'original',
                                    'required'  => TRUE,
                                    'category'  => __('Color')),
                'theme_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color that styles the mobile browser interface.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

                /*'admin_theme' => array(     'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Change the admin color theme'),
                                            'options'   => array(   'bootstrap' => 'Original',
                                                                    'cerulean'  => 'Dark Blue',
                                                                    'cosmo'     => 'Metro Style',
                                                                    'spacelab'  => 'Nice Grey',
                                                                    'united'    => 'Purple / Orange',
                                                                ),
                                            'default'   => 'bootstrap',
                                            'required'  => TRUE),*/

                'body_font' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Body Font'),
                                            'options'   => array(   '' => 'Default',
                                                    '//fonts.googleapis.com/css?family=Open+Sans:400,700|Open Sans' => 'Open Sans',
                                                    '//fonts.googleapis.com/css?family=Roboto:400,700|Roboto' => 'Roboto',
                                                    '//fonts.googleapis.com/css?family=Lato:400,700|Lato' => 'Lato',
                                                    '//fonts.googleapis.com/css?family=Slabo+27px:400,700|Slabo 27px' => 'Slabo 27px',
                                                    '//fonts.googleapis.com/css?family=Oswald:400,700|Oswald' => 'Oswald',
                                                    '//fonts.googleapis.com/css?family=Roboto+Condensed:400,700|Roboto Condensed' => 'Roboto Condensed',
                                                    '//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source Sans Pro' => 'Source Sans Pro',
                                                    '//fonts.googleapis.com/css?family=Montserrat:400,700|Montserrat' => 'Montserrat',
                                                    '//fonts.googleapis.com/css?family=Lora:400,700|Lora' => 'Lora',
                                                    '//fonts.googleapis.com/css?family=PT+Sans:400,700|PT Sans' => 'PT Sans',
                                                    '//fonts.googleapis.com/css?family=Raleway:400,700|Raleway' => 'Raleway',
                                                    '//fonts.googleapis.com/css?family=Open+Sans+Condensed:400,700|Open Sans Condensed' => 'Open Sans Condensed',
                                                    '//fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid Sans' => 'Droid Sans',
                                                    '//fonts.googleapis.com/css?family=Ubuntu:400,700|Ubuntu' => 'Ubuntu',
                                                    '//fonts.googleapis.com/css?family=Droid+Serif:400,700|Droid Serif' => 'Droid Serif',
                                                    '//fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto Slab' => 'Roboto Slab',
                                                    '//fonts.googleapis.com/css?family=Merriweather:400,700|Merriweather' => 'Merriweather',
                                                    '//fonts.googleapis.com/css?family=Arimo:400,700|Arimo' => 'Arimo',
                                                    '//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700|PT Sans Narrow' => 'PT Sans Narrow',
                                                    '//fonts.googleapis.com/css?family=Noto+Sans:400,700|Noto Sans' => 'Noto Sans'
                                                                ),
                                            'default'   => '',
                                            'category'  => __('Typography')),

                'breadcrumb' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display breadcrumb'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'fixed_toolbar' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Header tool bar gets fixed in the top'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '1',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'logo_url' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your Logo. Recommended size 250px x 40px and file format PNG. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                'favicon_url' => array(     'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your favicon. Recommended size 57px x 57px. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General')),

    			'apple-touch-icon' => array('type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your apple-touch-icon. Recommended size 57px x 57px. Leave blank for none.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                'default_profile_image' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your default profile image.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                'num_home_latest_ads' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Numbers of ads to display in home slider'),
                                            'default'   => 21,
                                            'required'  => TRUE,
                                            'category'  => __('Homepage')),

                'sidebar_position' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Where you want the sidebar to appear'),
                                            'options'   => array(   'none' => __('None'),
                                                                    'right' => __('Right side'),
                                                                    'left'  => __('Left side'),
                                                                ),
                                            'default'   => 'right',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),
                'listing_slider' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display slider in listing'),
                                            'options'   => array(
                                                                    '0'  => __('None'),
                                                                    '1' => __('Default'),
                                                                    '2'  => __('Featured'),
                                                                    '3' => __('Featured Random')
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),
                'listgrid' => array(   'type'      => 'text',
                                        'display'   => 'select',
                                        'label'     => __('Default state for list/grid in listing'),
                                        'options'   => array(
                                                                '0'  => __('Grid'),
                                                                '1' => __('List'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),
                'infinite_scroll' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Infinite scroll'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Listing')),

                'category_badge' => array(  'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Disable category counter badge'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'landing_single_ad' =>array('type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Hide header and footer on single ad, user profile page and guest checkout page'),
                                            'options'   => array(
                                                                    '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('Layout')),

                'home_slider_img_1' => array(       'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Homepage Header Slider Image 1'),
                                                    'default'   => 'https://i.imgur.com/UGAWor3.jpg',
                                                    'category'  => __('Homepage')),
                'home_slider_title_1' => array(     'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Title 1'),
                                                    'placeholder'   => 'Lorem ipsum dolor sit amet',
                                                    'category'  => __('Homepage')),
                'home_slider_subtitle_1' => array(  'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Subtitle 1'),
                                                    'placeholder'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tristique est sit amet diam interdum semper. ',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_title_1' => array( 'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA Title 1'),
                                                    'placeholder'   => 'Buy Now - $199',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_url_1' => array(   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA URL 1'),
                                                    'placeholder'   => '/',
                                                    'category'  => __('Homepage')),
                'home_slider_img_2' => array(       'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Homepage Header Slider Image 2'),
                                                    'default'   => 'https://i.imgur.com/E08ScLf.jpg',
                                                    'category'  => __('Homepage')),
                'home_slider_title_2' => array(     'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Title 2'),
                                                    'placeholder'   => 'Mauris semper tincidunt suscipit',
                                                    'category'  => __('Homepage')),
                'home_slider_subtitle_2' => array(  'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Subtitle 2'),
                                                    'placeholder'   => 'Donec tristique est sit amet diam interdum semper. Vestibulum condimentum ante urna, vel interdum odio accumsan id.',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_title_2' => array( 'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA Title 2'),
                                                    'placeholder'   => 'Buy Now - $199',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_url_2' => array(   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA URL 2'),
                                                    'placeholder'   => '/',
                                                    'category'  => __('Homepage')),
                'home_slider_img_3' => array(       'type'      => 'text',
                                                    'display'   => 'logo',
                                                    'label'     => __('Homepage Header Slider Image 3'),
                                                    'default'   => 'https://i.imgur.com/2uKBVFn.jpg',
                                                    'category'  => __('Homepage')),
                'home_slider_title_3' => array(     'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Title 3'),
                                                    'placeholder'   => 'Phasellus et nisi tincidunt',
                                                    'category'  => __('Homepage')),
                'home_slider_subtitle_3' => array(  'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider Subtitle 3'),
                                                    'placeholder'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum ante urna, vel interdum odio accumsan id.',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_title_3' => array( 'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA Title 3'),
                                                    'placeholder'   => 'Buy Now - $479',
                                                    'category'  => __('Homepage')),
                'home_slider_cta_url_3' => array(   'type'      => 'text',
                                                    'display'   => 'text',
                                                    'label'     => __('Homepage Header Slider CTA URL 3'),
                                                    'placeholder'   => '/',
                                                    'category'  => __('Homepage')),
                'home_hero_title' => array( 'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage Hero Title'),
                                            'default'   => 'It’s Lorem ipsum dolor sit amet consectetur',
                                            'category'  => __('Homepage')),
                'home_hero_desc' => array(  'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage Hero Description'),
                                            'default'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tristique est sit amet diam interdum semper. Vestibulum condimentum ante urna, vel interdum odio accumsan id.',
                                            'category'  => __('Homepage')),
                'home_cta_title' => array(  'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Homepage CTA Title'),
                                            'default'   => 'Lorem trist iquest siamet diam ipsum dolor sitamt',
                                            'category'  => __('Homepage')),
                'home_cta_btn1_anchor' => array('type'      => 'text',
                                                'display'   => 'text',
                                                'label'     => __('Homepage CTA button 1 Title'),
                                                'default'   => 'Download',
                                                'category'  => __('Homepage')),
                'home_cta_btn1_url' => array(   'type'      => 'text',
                                                'display'   => 'text',
                                                'label'     => __('Homepage CTA button 1 URL'),
                                                'default'   => '/',
                                                'category'  => __('Homepage')),
                'home_cta_btn2_anchor' => array('type'      => 'text',
                                                'display'   => 'text',
                                                'label'     => __('Homepage CTA button 2 Title'),
                                                'default'   => 'Get it now',
                                                'category'  => __('Homepage')),
                'home_cta_btn2_url' => array(   'type'      => 'text',
                                                'display'   => 'text',
                                                'label'     => __('Homepage CTA button 2 URL'),
                                                'default'   => '/',
                                                'category'  => __('Homepage')),
                'header_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Header banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'footer_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Footer banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                'listing_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Listing random position banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Listing')),
                'homepage_html' => array(   'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Homepage Only Header, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('Homepage')),
                'rtl' => array(             'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Content shift right to left'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),
                'cdn_files' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Uses CDN for CSS/JS'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),

                'amp_top_bar_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color that styles the top bar of the AMP pages.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

                'amp_custom_color' => array(    'type'      => 'text',
                                            'display'   => 'color',
                                            'label'     => __('Select the color of the AMP pages.'),
                                            'default'   => '',
                                            'category'  => __('Color')),

);
