<?php defined('SYSPATH') or die('No direct access allowed.');


/**
 * custom options for the theme
 * @var array
 */
return array(    'premium' => array( 'type'      => 'numeric',
                                                'display'   => 'hidden',
                                                'default'   => 1,
                                                'required'  => TRUE,
                                                'category'  => __('General')),


                            'theme_color_main' => array(    'type'      => 'text',
                                                            'display'   => 'select',
                                                            'label'     => __('Change the main color scheme and style of the theme'),
                                                            'options'   => array(   'colorama' => 'Custom green',
                                                                                    'grey' => 'Grey',
                                                                                    'black' => 'Black',
                                                                                ),
                                                            'default'   => 'colorama',
                                                            'required'  => TRUE,
                                                            'category'  => __('Color')),

                            'theme_headers' =>  array(  'type'      => 'text',
                                                        'display'   => 'select',
                                                        'label'     => __('Change the header color scheme and style of the theme'),
                                                        'options'   => array(   'a' => 'Grey',
                                                                                'b' => 'Black',
                                                                                    ),
                                                        'default'   => 'b',
                                                        'required'  => TRUE,
                                                        'category'  => __('Color')),

                            'theme_list_elements' =>  array(    'type'      => 'text',
                                                                'display'   => 'select',
                                                                'label'     => __('Change the theme of List Elements'),
                                                                'options'   => array(   'a' => 'Grey',
                                                                                        'b' => 'Black',
                                                                                            ),
                                                                'default'   => '',
                                                                'required'  => TRUE,
                                                                'category'  => __('Color')),

                            'theme_featured_elements' =>  array(    'type'      => 'text',
                                                                    'display'   => 'select',
                                                                    'label'     => __('Change the theme of Featured Elements'),
                                                                    'options'   => array(   'a' => 'Grey',
                                                                                            'b' => 'Black',
                                                                                                ),
                                                                    'default'   => '',
                                                                    'required'  => TRUE,
                                                                    'category'  => __('Color')),

                            'logo_url' => array(        'type'      => 'text',
                                                        'display'   => 'logo',
                                                        'label'     => __('Upload your Logo. Recommended size 250px x 40px and file format PNG. Leave blank for none.'),
                                                        'default'   => '',
                                                        'category'  => __('General')),

                            'favicon_url' => array(     'type'      => 'text',
                                                        'display'   => 'logo',
                                                        'label'     => __('Upload your favicon. Leave blank for none.'),
                                                        'default'   => '',
                                                        'category'  => __('General')),

                            'apple-touch-icon' => array('type'      => 'text',
                                                        'display'   => 'logo',
                                                        'label'     => __('Upload your apple-touch-icon. Recommended size 57px x 57px. Leave blank for none.'),
                                                        'default'   => '',
                                                        'category'  => __('General')),

                            'default_profile_image' => array(   'type'      => 'text',
                                            'display'   => 'logo',
                                            'label'     => __('Upload your default profile image.'),
                                            'default'   => '',
                                            'category'  => __('General')),

                            'num_home_latest_ads' => array(   'type'      => 'text',
                                                        'display'   => 'text',
                                                        'label'     => __('Numbers of ads to display in home slider'),
                                                        'default'   => 8,
                                                        'required'  => TRUE,
                                                        'category'  => __('Homepage')),

                            'slider_in_home' => array(   'type'      => 'text',
                                                        'display'   => 'select',
                                                        'label'     => __('Display slider in home'),
                                                        'options'   => array(   '1' => __('Yes'),
                                                                                '0'  => __('No'),
                                                                            ),
                                                        'default'   => '1',
                                                        'required'  => TRUE,
                                                        'category'  => __('Homepage')),

                            'header_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Header banner, allows HTML'),
                                            'default'   => '',
                                            'category'  => __('General')),
                            'footer_ad' => array(       'type'      => 'text',
                                                        'display'   => 'textarea',
                                                        'label'     => __('Footer banner, allows HTML'),
                                                        'default'   => '',
                                                        'category'  => __('General')),
                            'listing_ad' => array(       'type'      => 'text',
                                                        'display'   => 'textarea',
                                                        'label'     => __('Listing random position banner, allows HTML'),
                                                        'default'   => '',
                                                        'category'  => __('Listing')),
                            'listing_slider' => array(  'type'      => 'text',
                                                        'display'   => 'select',
                                                        'label'     => __('Display slider in listing'),
                                                        'options'   => array(
                                                            '0'  => __('None'),
                                                            '1' => __('Default'),
                                                            '2'  => __('Featured'),
                                                            '3' => __('Featured Random')
                                                        ),
                                                        'default'   => '0',
                                                        'required'  => TRUE,
                                                        'category'  => __('Listing')),
                            'homepage_html' => array(   'type'      => 'text',
                                                        'display'   => 'textarea',
                                                        'label'     => __('Homepage Only Header, allows HTML'),
                                                        'default'   => '',
                                                        'category'  => __('Homepage')),
                            'upload_images_mobile' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Allow uploading images in publish new.'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),
                            'rtl' => array(             'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Content shift right to left'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),
                            'cdn_files' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Uses CDN for CSS/JS'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ),
                                            'default'   => '0',
                                            'required'  => TRUE,
                                            'category'  => __('General')),


);
